twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [
        'bootstrap_5_layout.html.twig',
    ]
    globals:
        client_path: '%app.client.url%'
        mailer_email: '%mailer_email%'
        artist_name: '%artist_name%'
        imagesPath: '/assets/email/images'
        app_name: '%app.name%'
        assets_base_directory: '%assets_base_directory%'
        mailContentService: '@app.mailcontent.service'

    paths:
        '%kernel.project_dir%/public/assets/email/images': images
        '%kernel.project_dir%/public/assets/email/css': styles

when@test:
    twig:
        strict_variables: true
